### ISSUE TITLE
Game unexpectedly crashes after 2 hours

### ISSUE THREAD

**Issue by Lachrymogenic** [FinalForEach/Cosmic-Reach-Issue-Tracker#107]
No further comment.

```
* Game started: true
* Game version: 0.1.2
* Ran for : 2 hours, 20 minutes, 35 seconds
* Current time: 2024-03-12 at 16:08:59.760583210Z[Europe/London]
* Operating system: Linux 6.5.5-060505-generic
* Arch: amd64
* Java VM name: OpenJDK 64-Bit Server VM
* Java runtime version: 21.0.2+13-58
* System user language: en
* CPU model: AMD Ryzen 5 3400G with Radeon Vega Graphics
* Save location free space: 179.232 GB
* Save location total space: 438.548 GB
* Available processors: 8
* Native heap use: 3.103 GB
* Java heap use: 3.103 GB
* Max memory available: 3.391 GB
* RAM available: 13.559 GB
* getGLVersion: 
Type: OpenGL
Version: 4:6:0
Vendor: AMD
Renderer: AMD Radeon Vega 11 Graphics (radeonsi, raven, LLVM 15.0.7, DRM 3.54, 6.5.5-060505-generic)
* Exception logs: 
java.util.NoSuchElementException: 142
    at com.badlogic.gdx.utils.Array$ArrayIterator.next(Array.java:644)
    at finalforeach.cosmicreach.rendering.WorldRenderer.getChunksToRender(WorldRenderer.java:170)
    at finalforeach.cosmicreach.rendering.WorldRenderer.render(WorldRenderer.java:286)
    at finalforeach.cosmicreach.world.World.render(World.java:122)
    at finalforeach.cosmicreach.gamestates.InGame.render(InGame.java:157)
    at finalforeach.cosmicreach.BlockGame.render(BlockGame.java:89)
    at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:387)
    at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:193)
    at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:167)
    at finalforeach.cosmicreach.lwjgl3.Lwjgl3Launcher.createApplication(Lwjgl3Launcher.java:290)
    at finalforeach.cosmicreach.lwjgl3.Lwjgl3Launcher.main(Lwjgl3Launcher.java:69)
```

**Comment by Lachrymogenic** [comment]
Playing for a while and starting to notice that this game has memory leaks

**Comment by Moortu** [comment]
defo has a memory leak somewhere

**Comment by FinalForEach** [comment]
This specific exception has been fixed, so closing the issue.
