### ISSUE TITLE
Renaming a world folder to contain unicode characters past U+00FF (ÿ) will crash the game when attempting to render the world selection screen

### ISSUE THREAD

**Issue by Moonyol** [FinalForEach/Cosmic-Reach-Issue-Tracker#119]
Here I used Ā (U+0100) which is the 1st character that crashes

```
* Game started: true
* Game version: 0.1.7
* Ran for : 2 seconds, 326 ms
* Current time: 2024-03-16 at 20:42:08.925223200Z[Europe/London]
* Operating system: Windows 10 10.0
* Arch: amd64
* Java VM name: OpenJDK 64-Bit Server VM
* Java runtime version: 21.0.2+13-58
* System user language: en
* CPU model: Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz
* Save location free space: 707.328 GB
* Save location total space: 953 GB
* Available processors: 12
* Native heap use: 21 MB
* Java heap use: 21 MB
* Max memory available: 7.98 GB
* RAM available: 31.912 GB
* getGLVersion: 
Type: OpenGL
Version: 4:6:0
Vendor: NVIDIA Corporation
Renderer: NVIDIA GeForce GTX 1660/PCIe/SSE2
* Exception logs: 
java.lang.ArrayIndexOutOfBoundsException: Index 256 out of bounds for length 256
    at finalforeach.cosmicreach.ui.UIElement.drawText(UIElement.java:188)
    at finalforeach.cosmicreach.gamestates.GameState.drawUIElements(GameState.java:87)
    at finalforeach.cosmicreach.gamestates.WorldSelectionMenu.render(WorldSelectionMenu.java:206)
    at finalforeach.cosmicreach.BlockGame.render(BlockGame.java:97)
    at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:387)
    at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:193)
    at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:167)
    at finalforeach.cosmicreach.lwjgl3.Lwjgl3Launcher.createApplication(Lwjgl3Launcher.java:78)
    at finalforeach.cosmicreach.lwjgl3.Lwjgl3Launcher.main(Lwjgl3Launcher.java:68)

```

**Comment by FinalForEach** [comment]
Should be fixed for 0.1.8, closing
