### ISSUE TITLE
Texture Loading Issue? Please Help!!!

### ISSUE THREAD

**Issue by scarzyz** [FinalForEach/Cosmic-Reach-Issue-Tracker#140]
I have been wanting to play Cosmic Reach, however, the screen flashes with textures from across the map while I move my camera and my player around. Please be careful with the video, as it may induce seizures. I was hoping someone might have any ideas? Thank you so much for any help that y'all might have! I saw some others had an issue similar to myself. Before this, I have also tried using different lighting types, as well as uninstalling and reinstalling the game. I am on the most recent version of the game, 0.1.28, for Windows.

I also have the warning from the debug crash report if that will help:

* Prestart error logs: 
[LWJGL] OpenGL debug message
    ID: 0x0
    Source: SHADER COMPILER
    Type: OTHER
    Severity: MEDIUM
    Message: SHADER_ID_COMPILE other warning has been generated. GLSL compile warning(s) for shader 10, "": WARNING: 0:1: '' :  #version directive missing

[LWJGL] OpenGL debug message
    ID: 0x0
    Source: SHADER COMPILER
    Type: OTHER
    Severity: MEDIUM
    Message: SHADER_ID_COMPILE other warning has been generated. GLSL compile warning(s) for shader 11, "": WARNING: 0:5: '' :  #version directive missing

* Exception logs: 
java.lang.RuntimeException: Caused a manual crash, not a bug!
    at finalforeach.cosmicreach.gamestates.OptionsMenu$9.onClick(OptionsMenu.java:242)
    at finalforeach.cosmicreach.ui.UIElement.drawBackground(UIElement.java:144)
    at finalforeach.cosmicreach.gamestates.GameState.drawUIElements(GameState.java:100)
    at finalforeach.cosmicreach.gamestates.OptionsMenu.render(OptionsMenu.java:285)
    at finalforeach.cosmicreach.BlockGame.render(BlockGame.java:172)
    at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:387)
    at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:193)
    at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:167)
    at finalforeach.cosmicreach.lwjgl3.Lwjgl3Launcher.createApplication(Lwjgl3Launcher.java:54)
    at finalforeach.cosmicreach.lwjgl3.Lwjgl3Launcher.main(Lwjgl3Launcher.java:44)

https://github.com/FinalForEach/Cosmic-Reach-Issue-Tracker/assets/169213580/90241f9e-2db1-4c79-9d89-1ce165ae13a4

**Comment by FinalForEach** [comment]
Hi, thank you for your report, I'm going to assume you are on an integrated GPU, such as a laptop (you didn't give the full logs) this is a known bug and I will be making alternative renderers available in the next update so that this doesn't happen when choosing them.

**Comment by scarzyz** [comment]
Thank you so much, good luck with all your work!!! Take your time, no rush at all :)

**Comment by FinalForEach** [comment]
The triangle bugs have been fixed since the end of pre-alpha, so closing this issue now
