### ISSUE TITLE
game crashes when credits button is clicked

### ISSUE THREAD

**Issue by thurm64** [FinalForEach/Cosmic-Reach-Issue-Tracker#159]
Self-explanatory. Click the credits button on main menu. It crashes.
Logs:
```
* Game started: true
* Game version: 0.3.7
* Ran for : 13 seconds, 106 ms
* Current time: 2024-11-17 at 21:06:37.810040400-05:00[America/New_York]
* Operating system: Windows 10 10.0
* Arch: amd64
* Java VM name: OpenJDK 64-Bit Server VM
* Java runtime version: 21.0.2+13-58
* System user language: en
* CPU model: AMD Ryzen 7 3750H with Radeon Vega Mobile Gfx
* Save location free / total space: 15.604 GB / 237.568 GB
* Available processors: 8
* Native heap use: 14 MB
* Java heap use: 14 MB
* Max memory available: 3.484 GB
* RAM available: 13.937 GB
* getGLVersion: 
Type: OpenGL
Version: 4:6:0
Vendor: NVIDIA Corporation
Renderer: NVIDIA GeForce GTX 1660 Ti/PCIe/SSE2
* Exception logs: 
java.lang.ClassCastException: class [Ljava.lang.Object; cannot be cast to class [Ljava.lang.String; ([Ljava.lang.Object; and [Ljava.lang.String; are in module java.base of loader 'bootstrap')
    at finalforeach.cosmicreach.gamestates.CreditsMenu.create(CreditsMenu.java:67)
    at finalforeach.cosmicreach.gamestates.GameState.lambda$switchToGameState$0(GameState.java:87)
    at finalforeach.cosmicreach.Threads.runOnMainThread(Threads.java:19)
    at finalforeach.cosmicreach.gamestates.GameState.switchToGameState(GameState.java:72)
    at finalforeach.cosmicreach.gamestates.MainMenu$6.onClick(MainMenu.java:130)
    at finalforeach.cosmicreach.ui.UIElement.drawBackground(UIElement.java:145)
    at finalforeach.cosmicreach.gamestates.GameState.drawUIElements(GameState.java:129)
    at finalforeach.cosmicreach.gamestates.MainMenu.render(MainMenu.java:229)
    at finalforeach.cosmicreach.BlockGame.render(BlockGame.java:126)
    at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:387)
    at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:193)
    at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:167)
    at finalforeach.cosmicreach.lwjgl3.Lwjgl3Launcher.createApplication(Lwjgl3Launcher.java:103)
    at finalforeach.cosmicreach.lwjgl3.Lwjgl3Launcher.main(Lwjgl3Launcher.java:91)
```

**Comment by FinalForEach** [comment]
Confirmed and fixed for the next update.
