### ISSUE TITLE
Game crashes when exiting using "Return to Main Menu"

### ISSUE THREAD

**Issue by Za9-118** [FinalForEach/Cosmic-Reach-Issue-Tracker#160]
Here is the crashlog:

```
* Game started: true
* Game version: 0.3.7
* Ran for : 11 minutes, 2 seconds
* Current time: 2024-11-30 at 18:48:48.882614300+01:00[CENSORED]
* Operating system: Windows 11 10.0
* Arch: amd64
* Java VM name: OpenJDK 64-Bit Server VM
* Java runtime version: 21.0.2+13-58
* System user language: en
* CPU model: Intel(R) Pentium(R) Silver N6000 @ 1.10GHz
* Save location free / total space: 32.96 GB / 117.662 GB
* Available processors: 4
* Native heap use: 20 MB
* Java heap use: 20 MB
* Max memory available: 1.939 GB
* RAM available: 7.753 GB
* getGLVersion: 
Type: OpenGL
Version: 4:6:0
Vendor: Intel
Renderer: Intel(R) HD Graphics Gen11
* Prestart error logs: 
[LWJGL] OpenGL debug message
    ID: 0x0
    Source: SHADER COMPILER
    Type: OTHER
    Severity: MEDIUM
    Message: SHADER_ID_COMPILE other warning has been generated. GLSL compile warning(s) for shader 22, "": WARNING: 0:1: '' :  #version directive missing


[LWJGL] OpenGL debug message
    ID: 0x0
    Source: SHADER COMPILER
    Type: OTHER
    Severity: MEDIUM
    Message: SHADER_ID_COMPILE other warning has been generated. GLSL compile warning(s) for shader 23, "": WARNING: 0:5: '' :  #version directive missing


[LWJGL] OpenGL debug message
    ID: 0x0
    Source: SHADER COMPILER
    Type: OTHER
    Severity: MEDIUM
    Message: SHADER_ID_COMPILE other warning has been generated. GLSL compile warning(s) for shader 25, "": WARNING: 0:1: '' :  #version directive missing


[LWJGL] OpenGL debug message
    ID: 0x0
    Source: SHADER COMPILER
    Type: OTHER
    Severity: MEDIUM
    Message: SHADER_ID_COMPILE other warning has been generated. GLSL compile warning(s) for shader 26, "": WARNING: 0:5: '' :  #version directive missing



* Exception logs: 
java.lang.ClassCastException: class [Ljava.lang.Object; cannot be cast to class [Ljava.lang.String; ([Ljava.lang.Object; and [Ljava.lang.String; are in module java.base of loader 'bootstrap')
    at finalforeach.cosmicreach.gamestates.CreditsMenu.create(CreditsMenu.java:67)
    at finalforeach.cosmicreach.gamestates.GameState.lambda$switchToGameState$0(GameState.java:87)
    at finalforeach.cosmicreach.Threads.runOnMainThread(Threads.java:19)
    at finalforeach.cosmicreach.gamestates.GameState.switchToGameState(GameState.java:72)
    at finalforeach.cosmicreach.gamestates.MainMenu$6.onClick(MainMenu.java:130)
    at finalforeach.cosmicreach.ui.UIElement.drawBackground(UIElement.java:145)
    at finalforeach.cosmicreach.gamestates.GameState.drawUIElements(GameState.java:129)
    at finalforeach.cosmicreach.gamestates.MainMenu.render(MainMenu.java:229)
    at finalforeach.cosmicreach.BlockGame.render(BlockGame.java:126)
    at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:387)
    at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:193)
    at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:167)
    at finalforeach.cosmicreach.lwjgl3.Lwjgl3Launcher.createApplication(Lwjgl3Launcher.java:103)
    at finalforeach.cosmicreach.lwjgl3.Lwjgl3Launcher.main(Lwjgl3Launcher.java:91)
```

**Comment by FinalForEach** [comment]
Should be fixed now.
