### ISSUE TITLE
Game Crashes when trying to open saves directory

### ISSUE THREAD

**Issue by kuandai** [FinalForEach/Cosmic-Reach-Issue-Tracker#95]
This problem occurs when launching the jar on Fedora Workstation 38

How to reproduce:
Launch Game using the jarfile
Press "Open Save Directory"

Then the game crashes

This is the terminal output:

```
[ian@fedora Release 0.0.14]$ java -jar *.jar
GL_VENDOR: AMD
GL_RENDERER: AMD Radeon Vega 8 Graphics (raven, LLVM 16.0.6, DRM 3.57, 6.7.5-100.fc38.x86_64)
GL_VERSION: 4.6 (Compatibility Profile) Mesa 23.1.9
GL_NUM_EXTENSIONS: 314
Loading shaders/chunk.vert.glsl
Loading shaders/common/bitUnpacker.glsl
Loading shaders/chunk.frag.glsl
Compiling shader(chunk.vert.glsl, chunk.frag.glsl)...
Loaded uniform: GL_FLOAT_MAT4 u_projViewTrans at location=0
Loaded uniform: GL_FLOAT_VEC3 skyAmbientColor at location=1
Loaded uniform: GL_SAMPLER_2D texDiffuse at location=2

Loading shaders/chunk-water.vert.glsl
Loading shaders/common/bitUnpacker.glsl
Loading shaders/chunk-water.frag.glsl
Compiling shader(chunk-water.vert.glsl, chunk-water.frag.glsl)...
Loaded uniform: GL_FLOAT_MAT4 u_projViewTrans at location=0
Loaded uniform: GL_FLOAT u_time at location=1
Loaded uniform: GL_FLOAT_VEC3 cameraPosition at location=2
Loaded uniform: GL_FLOAT_VEC3 skyAmbientColor at location=3
Loaded uniform: GL_FLOAT_VEC3 skyColor at location=4
Loaded uniform: GL_SAMPLER_2D texDiffuse at location=5
Loaded uniform: GL_SAMPLER_2D noiseTex at location=6

Loading textures/blocks.png
Loading textures/noise.png
Loading shaders/block-selection.vert.glsl
Loading shaders/block-selection.frag.glsl
Compiling shader(block-selection.vert.glsl, block-selection.frag.glsl)...
Loaded uniform: GL_FLOAT_MAT4 u_projViewTrans at location=0
Loaded uniform: GL_FLOAT_VEC3 u_positionOffset at location=1
Loaded uniform: GL_SAMPLER_2D texDiffuse at location=2

Loading textures/block-selection.png
Loading shaders/sky-star.vert.glsl
Loading shaders/sky-star.frag.glsl
Compiling shader(sky-star.vert.glsl, sky-star.frag.glsl)...
Loaded uniform: GL_FLOAT_MAT4 u_projViewTrans at location=0

Loading textures/text-logo-hd.png
Loading sounds/ui/e-button-hover.ogg
Loading sounds/ui/e-button-click.ogg
[Controllers] added manager for application, 1 managers active
Switched to different gamestate
/home/ian/Cosmic Reach/Release 0.0.14
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class java.awt.Toolkit
	at java.desktop/java.awt.Component.<clinit>(Component.java:624)
	at finalforeach.cosmicreach.lwjgl3.Lwjgl3Launcher.main(Lwjgl3Launcher.java:265)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: Can't load library: /usr/lib/jvm/java-17-openjdk-17.0.9.0.9-3.fc38.x86_64/lib/libawt_xawt.so [in thread "main"]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2398)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1953)
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
	at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:315)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:285)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2403)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
	at java.base/java.lang.System.loadLibrary(System.java:1989)
	at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:1392)
	at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:1390)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at java.desktop/java.awt.Toolkit.loadLibraries(Toolkit.java:1389)
	at java.desktop/java.awt.Toolkit.initStatic(Toolkit.java:1427)
	at java.desktop/java.awt.Toolkit.<clinit>(Toolkit.java:1401)
	at java.desktop/java.awt.Desktop.isDesktopSupported(Desktop.java:329)
	at java.desktop/java.awt.Desktop.getDesktop(Desktop.java:303)
	at finalforeach.cosmicreach.gamestates.MainMenu$2.onClick(MainMenu.java:54)
	at finalforeach.cosmicreach.ui.UIElement.drawBackground(UIElement.java:133)
	at finalforeach.cosmicreach.gamestates.GameState.drawUIElements(GameState.java:83)
	at finalforeach.cosmicreach.gamestates.MainMenu.render(MainMenu.java:158)
	at finalforeach.cosmicreach.BlockGame.render(BlockGame.java:89)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:387)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:193)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:167)
	at finalforeach.cosmicreach.lwjgl3.Lwjgl3Launcher.createApplication(Lwjgl3Launcher.java:290)
	at finalforeach.cosmicreach.lwjgl3.Lwjgl3Launcher.main(Lwjgl3Launcher.java:69)
  
```

**Comment by kuandai** [comment]
GNOME 44, java version is `Red_Hat-17.0.9.0.9-4`, my file manager is nautilus.

**Comment by FinalForEach** [comment]
Are you able to run the native linux build? Does the problem occur there?

**Comment by kuandai** [comment]
I just tried the linux build for 0.1.0, and it works.

Does the jarfile version try to open a windows directory?

**Comment by FinalForEach** [comment]
The exact same. The native build just has a bundled JRE, so your installation was missing that underlying library it seems.

**Comment by kuandai** [comment]
That's interesting. What is the version of the bundled JRE?

**Comment by kuandai** [comment]
I installed openjdk 21 and now the button works, it's probably an issue with my jdk.
